name: Production deployment
on: [push]

jobs:
  notify:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build client
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci --silent
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          mattermost_channel: bots
          deployment_url: https://github.com/dataesr/mm-notifier-action/
